std::exception
OK


----
Should be OK
